# Generated by Django 3.0.5 on 2020-04-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200426_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='product_upc',
            field=models.CharField(max_length=500),
        ),
    ]
