# Generated by Django 3.0.5 on 2020-04-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200426_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master_drmsys',
            name='display_upc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='display_upc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='wholesale_price',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
