# Generated by Django 3.0.5 on 2020-04-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200426_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='track_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='volume_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
