# Generated by Django 3.0.5 on 2020-04-30 11:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200426_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(blank=True, max_length=600, null=True)),
                ('activity_period', models.CharField(blank=True, max_length=600, null=True)),
                ('retailer', models.CharField(blank=True, max_length=600, null=True)),
                ('territory', models.CharField(blank=True, max_length=600, null=True)),
                ('orchard_UPC', models.CharField(blank=True, max_length=600, null=True)),
                ('manufacturer_UPC', models.CharField(blank=True, max_length=600, null=True)),
                ('project_code', models.CharField(blank=True, max_length=600, null=True)),
                ('product_code', models.CharField(blank=True, max_length=600, null=True)),
                ('subaccount', models.CharField(blank=True, max_length=600, null=True)),
                ('imprint_label', models.CharField(blank=True, max_length=600, null=True)),
                ('artist_name', models.CharField(blank=True, max_length=600, null=True)),
                ('product_name', models.CharField(blank=True, max_length=600, null=True)),
                ('track_name', models.CharField(blank=True, max_length=600, null=True)),
                ('track_artist', models.CharField(blank=True, max_length=600, null=True)),
                ('isrc', models.CharField(blank=True, max_length=600, null=True)),
                ('volume', models.CharField(blank=True, max_length=600, null=True)),
                ('track', models.CharField(blank=True, max_length=600, null=True)),
                ('trans_type', models.CharField(blank=True, max_length=600, null=True)),
                ('trans_type_description', models.CharField(blank=True, max_length=600, null=True)),
                ('unit_price', models.CharField(blank=True, max_length=600, null=True)),
                ('discount', models.CharField(blank=True, max_length=600, null=True)),
                ('actual_price', models.CharField(blank=True, max_length=600, null=True)),
                ('quantity', models.CharField(blank=True, max_length=600, null=True)),
                ('total', models.CharField(blank=True, max_length=600, null=True)),
                ('adjusted_total', models.CharField(blank=True, max_length=600, null=True)),
                ('split_rate', models.CharField(blank=True, max_length=600, null=True)),
                ('label_share_net_receipts', models.CharField(blank=True, max_length=600, null=True)),
                ('ringtone_publishing', models.CharField(blank=True, max_length=600, null=True)),
                ('cloud_publishing', models.CharField(blank=True, max_length=600, null=True)),
                ('publishing', models.CharField(blank=True, max_length=600, null=True)),
                ('mech_administrative_fee', models.CharField(blank=True, max_length=600, null=True)),
                ('preferred_currency', models.CharField(blank=True, max_length=600, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=600, null=True)),
                ('file_doc', models.FileField(blank=True, upload_to='accounts/')),
                ('process_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('vendor', models.CharField(blank=True, max_length=600, null=True)),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
    ]
