# Generated by Django 3.0.5 on 2020-05-03 15:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_processedalbum_processedtrack'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=600, null=True)),
                ('file_doc', models.FileField(blank=True, upload_to='documents/')),
                ('process_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('which_doc', models.CharField(blank=True, max_length=600, null=True)),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='ProcessedAccount',
        ),
        migrations.DeleteModel(
            name='ProcessedAlbum',
        ),
        migrations.DeleteModel(
            name='ProcessedTrack',
        ),
        migrations.AddField(
            model_name='accounting',
            name='processed_day',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='accounting',
            name='updated_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='album',
            name='processed_day',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='updated_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='master_drmsys',
            name='processed_day',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='master_drmsys',
            name='updated_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='track',
            name='processed_day',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='updated_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
