# Generated by Django 3.0.5 on 2020-06-28 16:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200505_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedTrackFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=600, null=True)),
                ('file_doc', models.FileField(blank=True, upload_to='documents/processed_tracks')),
                ('process_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('which_doc', models.CharField(blank=True, max_length=600, null=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ProcessedDocument')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedAlbumFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=600, null=True)),
                ('file_doc', models.FileField(blank=True, upload_to='documents/processed_albums')),
                ('process_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('which_doc', models.CharField(blank=True, max_length=600, null=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ProcessedDocument')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedAccountFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=600, null=True)),
                ('file_doc', models.FileField(blank=True, upload_to='documents/processed_account')),
                ('process_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('which_doc', models.CharField(blank=True, max_length=600, null=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ProcessedDocument')),
            ],
        ),
    ]
