# Generated by Django 3.0.5 on 2021-02-14 11:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_verifiedlabels'),
    ]

    operations = [
        migrations.CreateModel(
            name='WrongLabelDocs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=600, null=True)),
                ('file_doc', models.FileField(blank=True, upload_to='documents/wrong_labels/')),
                ('process_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
