# Generated by Django 3.0.5 on 2021-04-12 05:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_missingrecordsdoc'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedLabelFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=600, null=True)),
                ('file_doc', models.FileField(blank=True, upload_to='documents/processed_label')),
                ('file_name_txt', models.CharField(blank=True, max_length=600, null=True)),
                ('file_doc_txt', models.FileField(blank=True, null=True, upload_to='documents/txt/processed_label')),
                ('process_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('which_doc', models.CharField(blank=True, max_length=600, null=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ProcessedDocument')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedArtistFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=600, null=True)),
                ('file_doc', models.FileField(blank=True, upload_to='documents/processed_artist')),
                ('file_name_txt', models.CharField(blank=True, max_length=600, null=True)),
                ('file_doc_txt', models.FileField(blank=True, null=True, upload_to='documents/txt/processed_artist')),
                ('process_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('which_doc', models.CharField(blank=True, max_length=600, null=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ProcessedDocument')),
            ],
        ),
    ]
