# Generated by Django 3.0.5 on 2020-11-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackEntries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('vid_id', models.CharField(blank=True, max_length=200, null=True)),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('duration', models.CharField(blank=True, max_length=500, null=True)),
                ('thumbnail', models.CharField(blank=True, max_length=500, null=True)),
                ('total_views', models.CharField(blank=True, max_length=500, null=True)),
                ('genre', models.CharField(blank=True, max_length=500, null=True)),
                ('likes', models.CharField(blank=True, max_length=500, null=True)),
                ('dislikes', models.CharField(blank=True, max_length=500, null=True)),
                ('commentCount', models.CharField(blank=True, max_length=500, null=True)),
                ('artist', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
